### ISSUE TITLE
About "The jps3d package should be integrated in the path_finding_util package."~

### ISSUE THREAD

**Issue by SuperHua888** [lis-epfl/multi_agent_pkgs#4]
Dr, could you give some support on this technical problem.

**Comment by ctoumieh** [comment]
Hi,

This is not a technical problem but rather a structuring improvement. Instead of heaving 2 packages one for path planning and one for path planning utilities, they should be merged into one. This does not pose any problem for the functioning of the package.

Best,
Charbel
